Updates file origination type selection description
network-for-good/nfg_csv_importer pull request #226
Opened 2023-02-16 16:27 UTC by aravindpudayoor

This PR is to update the description of the file origination types radio buttons. The default file description content contains "contacts and donations" but it does not make sense for all enclosing applications, for example in the case of auctions the bidder import description should contain "bidders" instead of "donations" or "contacts". It falls back to the `file_origination_type.description` if no custom description is present.

It will display the contents as

<img width="1792" alt="Screenshot 2023-02-17 at 12 21 29 PM" src="https://user-images.githubusercontent.com/2044699/219570878-3cc375d1-8f07-4b71-a885-8a346bd7b0ab.png">

Instead of 

<img width="1792" alt="Screenshot 2023-02-17 at 12 22 19 PM" src="https://user-images.githubusercontent.com/2044699/219571076-bf67086a-15ca-46a0-ad76-d9dd035e09f0.png">

2023-02-17 06:57 UTC, aravindpudayoor commented
> @aravindpudayoor Can you provide a description on why this is needed?

Done @hoenth.

2023-02-22 14:58 UTC, joseluistorres approved these changes
LGTM I left you some general questions

2023-02-22 14:58 UTC, joseluistorres commented on app/assets/javascripts/nfg_csv_importer/document_ready.coffee
> +  window.NfgCsvImporter.readyOrTurboLinksLoad = "turbo:load"
do you remember why this was needed? is this for when we have turbolinks vs turbo ?

2023-02-22 14:58 UTC, joseluistorres commented on app/presenters/nfg_csv_importer/onboarder/steps/file_origination_type_selection_presenter.rb
> +        def file_origination_type_description(file_origination_type:)
could the file_origination_type be any string? from your comment, right now a valid string is "contacts and donations" and "bidders"?

2023-02-23 14:01 UTC, hoenth requested changes

2023-02-23 14:01 UTC, hoenth commented on app/presenters/nfg_csv_importer/onboarder/steps/file_origination_type_selection_presenter.rb
> +        def file_origination_type_description(file_origination_type:)
This should have a spec that shows that the description can come from I18n or from the file_origination type if there is no entry in the the locales file for it. 

Also, the Readme should be updated to include instructions on how to override the description of the default file origination type.

2023-02-24 10:16 UTC, aravindpudayoor commented on app/presenters/nfg_csv_importer/onboarder/steps/file_origination_type_selection_presenter.rb
> +        def file_origination_type_description(file_origination_type:)
`file_origination_type` is the type that the types that are supported by the importer and same time it acts as the key for the locale. So here in the case of auctions, it will be `self_import_csv_xls` and we can mention the texts in the enclosing application(https://github.com/network-for-good/auctions/blob/feature/AIO-1499-import-bidders-to-auction/config/locales/views/onboarding/import_data.yml#L7). It will fallback to the default description if we don't have one in the enclosing application.

2023-02-24 10:16 UTC, aravindpudayoor commented on app/assets/javascripts/nfg_csv_importer/document_ready.coffee
> +  window.NfgCsvImporter.readyOrTurboLinksLoad = "turbo:load"
@joseluistorres Yes, as @hoenth said we are using Turbo in Auctions.

2023-02-24 13:15 UTC, aravindpudayoor commented on app/presenters/nfg_csv_importer/onboarder/steps/file_origination_type_selection_presenter.rb
> +        def file_origination_type_description(file_origination_type:)
@hoenth I have added the specs and updated the Readme as well. Please review.

2023-02-28 14:54 UTC, aravindpudayoor commented
@hoenth Could you please review this? If all looks good I can merge this to the parent branch and move auctions PR to beta for UAT.

2023-02-28 15:23 UTC, hoenth approved these changes
Just a small comment, but not a blocker. 

Eventually, we should look at being able to skip the file origination step if there is only one file origination type.

2023-02-28 15:23 UTC, hoenth commented on app/presenters/nfg_csv_importer/onboarder/steps/file_origination_type_selection_presenter.rb
> +          I18n.t("nfg_csv_importer.onboarding.import_data.file_origination_type_selection.file_origination_type_description.#{file_origination_type.type_sym}", default: file_origination_type.descript
One small thing here, usually it is easier to understand the I18n.t entry if you use a single key and a scope, i.e. 
`I18n.t(file_origination_type.type_sym, scope: %i[nfg_csv_importer onboarding import_data file_origination_type_selection file_origination_type_description], , default: file_origination_type.description)`

2023-02-28 15:23 UTC, hoenth commented on spec/presenters/nfg_csv_importer/onboarder/steps/file_origination_type_selection_presenter_spec.rb
> +        expect(subject).to eq I18n.t("nfg_csv_importer.onboarding.import_data.file_origination_type_selection.file_origination_type_description.self_import_csv_xls")
same change here as above on using scopes

2023-02-28 16:11 UTC, merged