[#NFG-781] adding import_title option for language change
network-for-good/nfg_csv_importer pull request #245
Opened 2024-11-07 15:49 UTC by ganeshmohan2021

2024-11-07 16:13 UTC, darwinwhaley approved these changes

2024-11-08 07:59 UTC, kcpavan requested changes
Ganesh spec not covering file changes please check.

2024-11-08 07:59 UTC, kcpavan commented on spec/views/onboarding/import_data/import_type.html.haml_spec.rb
> +    stub_template "onboarding/import_data/import_type.html.haml" => "= ui.nfg(title: @title)"
@ganeshmohan2021 I don't think this spec covers the file changes. if you revert view file changes I believe this spec  still passes.

2024-11-14 10:11 UTC, kcpavan approved these changes

2024-11-14 10:43 UTC, merged